# AWS, Terraform, dbt, Glue, Redshift & Apache Iceberg: An ETL Pipeline for Cloud Data Transformation and Modeling

This project builds an end-to-end data platform for DeFtunes, a subscription music application expanding into digital song purchases. It combines operational database data and API transactions into a reproducible AWS data lake and analytics-ready warehouse.

The implementation uses a medallion architecture with S3 landing storage, Apache Iceberg transformation tables, Redshift Spectrum, Terraform infrastructure as code, AWS Glue ETL jobs, and dbt models for the serving layer.

## Project Roadmap

1. [Introduction](#1)
2. [Data Sources](#2)
3. [Exploratory Data Analysis](#3)
4. [ETL Pipeline with AWS Glue and Terraform](#4)
   - [Landing Zone](#4-1)
   - [Transformation Zone](#4-2)
   - [Serving Zone](#4-3)
5. [Data Modeling with dbt and Redshift Spectrum](#5)
   - [Redshift Setup](#5-1)
   - [Redshift Validation](#5-2)
   - [dbt Setup](#5-3)
   - [Data Modeling](#5-4)

Reference  
This project is adapted from the Data Engineering Capstone Project provided by DeepLearning.AI; the AWS resources and datasets were supplied by the course strictly for educational and learning purposes.

<a id='1'></a>
## 1. Introduction

The pipeline integrates song metadata from a PostgreSQL RDS database with purchase-session and user data from DeFtunes APIs. It processes the sources through landing, transformation, and serving layers so that analysts can work with consistent, modeled data.

![Capstone_Diagram](images/Capstone-diagram.png)

### Architecture principles

- **Medallion data lake:** raw data is landed in S3, transformed into Iceberg tables, and exposed for analytics.
- **Reproducible infrastructure:** AWS resources and ETL jobs are provisioned with Terraform.
- **Analytics-ready serving layer:** Redshift Spectrum reads the Iceberg data, while dbt builds a star schema for downstream analysis.

In [1]:
import json
import requests
import pandas as pd

from IPython.display import HTML

%load_ext sql

### Environment Setup

The project environment is initialized through the repository setup script before running the pipeline components.

In the terminal run the following command to set up the environment:

<div style="padding: 10px 2px 0px 4px; border-radius: 4px;border: 1px solid #99999955;box-shadow: 4px 4px 6px rgba(52, 51, 51, 0.1);width: 50%;">

```bash
source scripts/setup.sh
```

</div>

<a id='2'></a>
## 2. Data Sources

The pipeline combines two complementary sources: a PostgreSQL operational database containing song metadata and a REST API containing purchase sessions and user attributes.

### 2.1. AWS Resource Discovery

CloudFormation outputs provide the temporary endpoints and bucket names required to connect the notebook to the project’s AWS resources.

In [2]:
with open('../.aws/aws_console_url', 'r') as file:
    aws_url = file.read().strip()

HTML(f'<a href="{aws_url}" target="_blank">GO TO AWS CONSOLE</a>')

The AWS console link is temporary, while the provisioned project resources remain available for the active environment.

CloudFormation outputs supply the PostgreSQL endpoint and scripts bucket used to configure the notebook and ETL jobs.

In [17]:
SCRIPTS_BUCKET_NAME = 'de-c4w4a1-730335556635-us-east-1-scripts'

In [3]:
RDSDBHOST = 'de-c4w4a1-rds.czg8aoiowmjf.us-east-1.rds.amazonaws.com'
RDSDBPORT = '5432'
RDSDBNAME = 'postgres'
RDSDBUSER = 'postgresuser'
RDSDBPASSWORD = 'adminpwrd'

postgres_connection_url = f'postgresql+psycopg2://{RDSDBUSER}:{RDSDBPASSWORD}@{RDSDBHOST}:{RDSDBPORT}/{RDSDBNAME}'
%sql {postgres_connection_url}

### 2.2. PostgreSQL Connectivity

The following query validates access to the DeFtunes operational database.

In [4]:
%%sql
SELECT schema_name
FROM information_schema.schemata;

 * postgresql+psycopg2://postgresuser:***@de-c4w4a1-rds.czg8aoiowmjf.us-east-1.rds.amazonaws.com:5432/postgres
6 rows affected.

[('public',),
 ('aws_s3',),
 ('aws_commons',),
 ('deftunes',),
 ('information_schema',),
 ('pg_catalog',)]

### 2.3. Song Metadata

The `deftunes.songs` table provides the song-level metadata used by the pipeline.

In [5]:
%%sql
SELECT *
FROM deftunes.songs
LIMIT 5;

 * postgresql+psycopg2://postgresuser:***@de-c4w4a1-rds.czg8aoiowmjf.us-east-1.rds.amazonaws.com:5432/postgres
5 rows affected.

[('TRMBFJC12903CE2A89', 'Mystery Babylon', 'SOGOPFY12AB018E5B1', 'Healing of All Nations', 'ARP06GY1187B98B0F0', '106e0414-95a7-45e9-8176-bbc938deed68', 'Yami Bolo', 146.49425, 0.4955022, 0.3224826, 2001, 8562838, -1, 0),
 ('TRMBFTN128F42665EA', 'Världen É Din', 'SOKFZOR12A8C1306B0', 'Omérta', 'ARZ6UKQ1187B9B0E35', 'a432b2e7-7598-419b-8760-e8accff3c725', 'The Latin Kings', 268.22485, 0.54002666, 0.42142987, 0, 3164205, -1, 0),
 ('TRMBFUD128F9318502', 'Working Underground', 'SOAVROI12AB0183312', 'My Land is Your Land', 'ARTOD2W1187B99FC16', '41b79e6f-9621-45c9-836c-9f08bedba4eb', 'Ashley Hutchings_ Ernesto De Pascale', 226.42892, 0.4131989, 0.33407375, 0, 3957236, -1, 0),
 ('TRMBFNG12903CEA2A8', 'Alien Bzzing', 'SOCWCQV12AC3DF9B21', "Uomini D'onore", 'ARUE65J1187B9AB4D9', '644feeb5-0ad9-457f-9d29-98474d42d9d3', 'Fireside', 345.96527, 0.48547184, 0.3672936, 1997, 8593681, -1, 0),
 ('TRMBFSN128F4259499', 'Repente', 'SOGWDNA12A8C139BFC', 'Limite das Aguas', 'ARS8WH31187B9B8B04', 'e02d67b8-b581-478e-be33-c988627e4050', 'Edu Lobo', 269.47873, 0.34406215, 0.0, 0, 2775420, -1, 0)]

### 2.4. Purchase API

The purchase API exposes session transactions and user information generated by the digital purchase workflow.

In [6]:
API_ENDPOINT = "ec2-44-194-55-36.compute-1.amazonaws.com"

The API also exposes interactive documentation at its `/docs` endpoint, which supports endpoint discovery and testing.

### 2.5. Session Transactions

The sessions endpoint returns transactional purchase-session data. The request below checks that the service responds successfully.

In [7]:
request_start_date = "2020-01-01"
request_end_date = "2020-03-01"
sessions_response = requests.get(f'http://{API_ENDPOINT}/sessions?start_date={request_start_date}&end_date={request_end_date}')
print(sessions_response.status_code)

200

The response is converted to JSON so individual transaction records can be inspected.

In [8]:
sessions_json = sessions_response.json()
print(json.dumps(sessions_json[0], indent=4))

{
    "user_id": "6b287203-7cab-4f1a-b1a4-2b5076294682",
    "session_id": "04a5e8ac-1acd-48dc-88b9-651c4ddf489c",
    "session_items": [
        {
            "song_id": "TRXKAGX128F9342DD7",
            "song_name": "3 Cards",
            "artist_id": "AR475MP1187B9A5449",
            "artist_name": "The Balancing Act",
            "price": 1.03,
            "currency": "USD",
            "liked": true,
            "liked_since": "2023-01-27T08:29:54.970697"
        },
        {
            "song_id": "TRUKGBT128F4292C9B",
            "song_name": "Parisian Walls (gband Version_ Barcelona)",
            "artist_id": "ARP9HJX1187FB4E5DA",
            "artist_name": "Apostle Of Hustle",
            "price": 1.31,
            "currency": "USD",
            "liked": true,
            "liked_since": "2023-06-14T00:27:55.876873"
        },
        {
            "song_id": "TRCPHWV128F4228647",
            "song_name": "Los Sabanales",
            "artist_id": "ARRLMTZ1187B9AB6DD",
            "artist_name": "Los Corraleros De Majagual",
            "price": 0.69,
            "currency": "USD",
            "liked": false,
            "liked_since": null
        },
        {
            "song_id": "TRMHNOY12903CDD075",
            "song_name": "Earth Messiah",
            "artist_id": "ARHS5PJ1187FB3C50D",
            "artist_name": "Cathedral",
            "price": 0.52,
            "currency": "USD",
            "liked": false,
            "liked_since": null
        },
        {
            "song_id": "TRIBGDZ128F425A019",
            "song_name": "Eu sei que vou te amar",
            "artist_id": "ARJK24L1187B9AFF5E",
            "artist_name": "Quarteto Em Cy",
            "price": 1.74,
            "currency": "USD",
            "liked": false,
            "liked_since": null
        },
        {
            "song_id": "TROJSDS128F146E6E2",
            "song_name": "Write My Ticket",
            "artist_id": "AR227JP1187FB375BC",
            "artist_name": "Tift Merritt",
            "price": 0.76,
            "currency": "USD",
            "liked": true,
            "liked_since": "2023-10-18T21:54:16.351564"
        }
    ],
    "user_agent": "Mozilla/5.0 (Windows NT 11.0) AppleWebKit/531.2 (KHTML, like Gecko) Chrome/19.0.859.0 Safari/531.2",
    "session_start_time": "2020-02-07T18:05:25.824461"
}

### 2.6. User Attributes

The users endpoint returns user-level attributes associated with the purchase workflow.

In [9]:
users_request = requests.get(f'http://{API_ENDPOINT}/users')
print(users_request.status_code)

200

In [10]:
users_json = users_request.json()
print(json.dumps(users_json[0], indent=4))

{
    "user_id": "a3141825-3a8c-4968-a3af-5362011ef7d5",
    "user_name": "Elizabeth",
    "user_lastname": "Carey",
    "user_location": [
        "46.32313",
        "-0.45877",
        "Niort",
        "FR",
        "Europe/Paris"
    ],
    "user_since": "2020-12-22T14:15:35.936090"
}

<a id='3'></a>
## 3. Exploratory Data Analysis

Initial profiling checks the structure, data types, distributions, and sample records from each source before transformation.

### 3.1. Song Data Sample

A sample of the PostgreSQL song table is loaded into pandas for local profiling.

In [11]:
songs_result = %sql SELECT *FROM deftunes.songs LIMIT 5
songs_df = songs_result.DataFrame()
songs_df.head()

 * postgresql+psycopg2://postgresuser:***@de-c4w4a1-rds.czg8aoiowmjf.us-east-1.rds.amazonaws.com:5432/postgres
5 rows affected.

,track_id,title,song_id,release,artist_id,artist_mbid,artist_name,duration,artist_familiarity,artist_hotttnesss,year,track_7digitalid,shs_perf,shs_work
0,TRMBFJC12903CE2A89,Mystery Babylon,SOGOPFY12AB018E5B1,Healing of All Nations,ARP06GY1187B98B0F0,106e0414-95a7-45e9-8176-bbc938deed68,Yami Bolo,146.49425,0.495502,0.322483,2001,8562838,-1,0
1,TRMBFTN128F42665EA,Världen É Din,SOKFZOR12A8C1306B0,Omérta,ARZ6UKQ1187B9B0E35,a432b2e7-7598-419b-8760-e8accff3c725,The Latin Kings,268.22485,0.540027,0.421430,0,3164205,-1,0
2,TRMBFUD128F9318502,Working Underground,SOAVROI12AB0183312,My Land is Your Land,ARTOD2W1187B99FC16,41b79e6f-9621-45c9-836c-9f08bedba4eb,Ashley Hutchings_ Ernesto De Pascale,226.42892,0.413199,0.334074,0,3957236,-1,0
3,TRMBFNG12903CEA2A8,Alien Bzzing,SOCWCQV12AC3DF9B21,Uomini D'onore,ARUE65J1187B9AB4D9,644feeb5-0ad9-457f-9d29-98474d42d9d3,Fireside,345.96527,0.485472,0.367294,1997,8593681,-1,0
4,TRMBFSN128F4259499,Repente,SOGWDNA12A8C139BFC,Limite das Aguas,ARS8WH31187B9B8B04,e02d67b8-b581-478e-be33-c988627e4050,Edu Lobo,269.47873,0.344062,0.000000,0,2775420,-1,0

### 3.2. Schema Profiling

`DataFrame.info()` summarizes column names, data types, and completeness for the song dataset.

In [12]:
print(songs_df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   track_id            5 non-null      object
 1   title               5 non-null      object
 2   song_id             5 non-null      object
 3   release             5 non-null      object
 4   artist_id           5 non-null      object
 5   artist_mbid         5 non-null      object
 6   artist_name         5 non-null      object
 7   duration            5 non-null      float64
 8   artist_familiarity  5 non-null      float64
 9   artist_hotttnesss   5 non-null      float64
 10  year                5 non-null      int64
 11  track_7digitalid    5 non-null      int64
 12  shs_perf            5 non-null      int64
 13  shs_work            5 non-null      int64
dtypes: float64(3), int64(4), object(7)
memory usage: 692.0+ bytes
None

### 3.3. Descriptive Statistics

`DataFrame.describe()` provides distribution summaries for the numerical fields.

In [13]:
songs_df.describe()

,duration,artist_familiarity,artist_hotttnesss,year,track_7digitalid,shs_perf,shs_work
count,5.000000,5.000000,5.000000,5.000000,5.000000e+00,5.0,5.0
mean,251.318404,0.455652,0.289056,799.600000,5.410676e+06,-1.0,0.0
std,72.768888,0.077219,0.166088,1094.898306,2.922813e+06,0.0,0.0
min,146.494250,0.344062,0.000000,0.000000,2.775420e+06,-1.0,0.0
25%,226.428920,0.413199,0.322483,0.000000,3.164205e+06,-1.0,0.0
50%,268.224850,0.485472,0.334074,0.000000,3.957236e+06,-1.0,0.0
75%,269.478730,0.495502,0.367294,1997.000000,8.562838e+06,-1.0,0.0
max,345.965270,0.540027,0.421430,2001.000000,8.593681e+06,-1.0,0.0

### 3.4. API Dataframes

The session and user JSON responses are normalized into pandas dataframes for inspection and downstream transformation.

In [14]:
session_df = pd.json_normalize(sessions_json)
session_df.head()

,user_id,session_id,session_items,user_agent,session_start_time
0,6b287203-7cab-4f1a-b1a4-2b5076294682,04a5e8ac-1acd-48dc-88b9-651c4ddf489c,"[{'song_id': 'TRXKAGX128F9342DD7', 'song_name'...",Mozilla/5.0 (Windows NT 11.0) AppleWebKit/531....,2020-02-07T18:05:25.824461
1,958ba0c2-cfc0-405e-a037-e644a4f34981,143e7ad2-e172-4590-aeaa-b50ee449e7b3,"[{'song_id': 'TRTHVBF128F935584D', 'song_name'...",Mozilla/5.0 (compatible; MSIE 5.0; Windows NT ...,2020-02-18T04:07:14.676057
2,7d13cf48-d80e-4cbe-8581-cce0fd301acf,6817fe3c-dd7f-4885-936b-dbbbb40923f2,"[{'song_id': 'TRJOSHE12903CDBA6F', 'song_name'...",Opera/9.90.(X11; Linux i686; cv-RU) Presto/2.9...,2020-02-21T22:25:56.407581
3,c06a8f89-4d88-4d71-83db-d567a69ef902,0383ce58-b47d-4923-abdd-d58d583d7bb2,"[{'song_id': 'TRSXSSK128F146EB46', 'song_name'...",Mozilla/5.0 (iPod; U; CPU iPhone OS 3_1 like M...,2020-02-19T04:27:31.957162
4,7118b8ac-75fe-426a-bf6c-09044ed64011,579ef099-ffed-410c-916a-05c222d7a734,"[{'song_id': 'TRRKCXY128F42B08EC', 'song_name'...",Opera/8.77.(X11; Linux x86_64; lb-LU) Presto/2...,2020-01-28T20:10:19.161986

In [15]:
user_df = pd.json_normalize(users_json)
user_df.head()

,user_id,user_name,user_lastname,user_location,user_since
0,a3141825-3a8c-4968-a3af-5362011ef7d5,Elizabeth,Carey,"[46.32313, -0.45877, Niort, FR, Europe/Paris]",2020-12-22T14:15:35.936090
1,923d55a6-26e9-4a61-b3e1-9c010e5db2cc,Joshua,Bishop,"[46.75451, 33.34864, Nova Kakhovka, UA, Europe...",2023-09-20T02:26:02.939528
2,ff728e8b-0c5b-48f7-a133-a30bf86c25e3,Joseph,Mcclain,"[32.57756, 71.52847, Mianwali, PK, Asia/Karachi]",2023-12-05T17:59:27.933557
3,9ae4d3aa-8cc8-42ac-beb4-5c9c799a392d,Jasmine,White,"[35.6803, 51.0193, Shahre Jadide Andisheh, IR,...",2024-06-18T17:56:45.626088
4,043010aa-9aad-4f63-8932-45eddada7856,Tyler,Ibarra,"[51.168, 7.973, Finnentrop, DE, Europe/Berlin]",2023-11-13T10:27:32.854497

<a id='4'></a>
## 4. ETL Pipeline with AWS Glue and Terraform

The ETL design separates ingestion, transformation, and serving concerns. AWS Glue executes the jobs, S3 stores the lake layers, and Terraform makes the infrastructure reproducible.

The pipeline includes database and API extraction jobs, Iceberg transformations for structured and nested data, and Redshift schemas for the serving layer.

<a id='4-1'></a>
### 4.1. Landing Zone

Three AWS Glue jobs ingest song data from PostgreSQL and session/user data from the API into the S3 landing layer. Terraform provisions the jobs and their supporting IAM, network, and storage resources.

The extraction scripts implement database and API ingestion. Landing data is organized by ingestion date to support traceability and partition-aware processing.

The Glue job configuration connects the API extraction jobs to the deployed API endpoint.

The extraction module defines the execution role, permissions, database network connection, inputs, and outputs required by the Glue jobs.

The root Terraform configuration wires the extraction module into the overall infrastructure and exposes its job outputs.

The extraction scripts are uploaded to the project’s scripts bucket before deployment.

In [18]:
!aws s3 cp ./terraform/assets/extract_jobs/de-c4w4a1-api-extract-job.py s3://{SCRIPTS_BUCKET_NAME}/de-c4w4a1-api-extract-job.py

upload: terraform/assets/extract_jobs/de-c4w4a1-api-extract-job.py to s3://de-c4w4a1-730335556635-us-east-1-scripts/de-c4w4a1-api-extract-job.py

In [19]:
!aws s3 cp ./terraform/assets/extract_jobs/de-c4w4a1-extract-songs-job.py s3://{SCRIPTS_BUCKET_NAME}/de-c4w4a1-extract-songs-job.py

upload: terraform/assets/extract_jobs/de-c4w4a1-extract-songs-job.py to s3://de-c4w4a1-730335556635-us-east-1-scripts/de-c4w4a1-extract-songs-job.py

Terraform deploys the landing-zone resources, after which the three extraction jobs can be executed.

<span style="font-size:16px"></span> In the terminal, go to the `terraform` folder and deploy the infrastructure with the following commands.

<div style="padding: 10px 2px 0px 4px; border-radius: 4px;border: 1px solid #99999955;box-shadow: 4px 4px 6px rgba(52, 51, 51, 0.1);width: 80%;">

```bash
cd terraform
terraform init
terraform plan
terraform apply -target=module.extract_job
```
</div>

The database and API extraction jobs populate the landing layer. Their run identifiers can be used to monitor completion and troubleshoot failures.

<span style="font-size:16px"><b>4.1.7.</b></span> You will get some outputs, in particular, you require the following three: `glue_api_users_extract_job`, `glue_sessions_users_extract_job` and `glue_rds_extract_job`. Those outputs correspond to the three glue jobs that will extract the data from the API endpoints and the database respectively. Run the following command three times in the terminal to execute the three Glue jobs. 

<div style="padding: 10px 2px 0px 4px; border-radius: 4px;border: 1px solid #99999955;box-shadow: 4px 4px 6px rgba(52, 51, 51, 0.1);width: 90%;">

```bash
aws glue start-job-run --job-name <JOB-NAME> | jq -r '.JobRunId'
```
</div>

For each run, replace `<JOB-NAME>` with one of the following values:
- `de-c4w4a1-api-users-extract-job`
- `de-c4w4a1-api-sessions-extract-job` 
- `de-c4w4a1-rds-extract-job`
  
You can run all three jobs in parallel, meaning you can execute the commands one after the other without waiting for each to finish before starting the next.


You should get `JobRunID` in the output of each command. Use this job run ID to track each job status by using this command, replacing the `<JOB-NAME>` and `<JobRunID>` placeholders.
<div style="padding: 10px 2px 0px 4px; border-radius: 4px;border: 1px solid #99999955;box-shadow: 4px 4px 6px rgba(52, 51, 51, 0.1);width: 90%;">

```bash
aws glue get-job-run --job-name <JOB-NAME> --run-id <JobRunID> --output text --query "JobRun.JobRunState"
```
</div>

Wait until the statuses of those three jobs change to `SUCCEEDED`.

Glue job logs and run status provide the primary diagnostics when an ingestion job requires investigation.

<a id='4-2'></a>
### 4.2. Transformation Zone

Transformation jobs read the raw landing data, standardize fields and nested structures, add processing metadata, and write Apache Iceberg tables to the S3 transformation layer.

The transformation scripts process song records and API JSON independently, producing queryable Iceberg datasets registered in the Glue Catalog.

The transformation module provisions the Glue resources needed to execute the Iceberg workloads.

The root Terraform configuration connects the transformation module to the rest of the pipeline.

The transformation scripts are uploaded to the scripts bucket before the module is deployed.

In [22]:
!aws s3 cp ./terraform/assets/transform_jobs/de-c4w4a1-transform-json-job.py s3://{SCRIPTS_BUCKET_NAME}/de-c4w4a1-transform-json-job.py

upload: terraform/assets/transform_jobs/de-c4w4a1-transform-json-job.py to s3://de-c4w4a1-730335556635-us-east-1-scripts/de-c4w4a1-transform-json-job.py

In [23]:
!aws s3 cp ./terraform/assets/transform_jobs/de-c4w4a1-transform-songs-job.py s3://{SCRIPTS_BUCKET_NAME}/de-c4w4a1-transform-songs-job.py

upload: terraform/assets/transform_jobs/de-c4w4a1-transform-songs-job.py to s3://de-c4w4a1-730335556635-us-east-1-scripts/de-c4w4a1-transform-songs-job.py

Terraform deploys the transformation resources like above, and the two Glue jobs then materialize the Iceberg tables from the landing data.

The JSON and song transformation jobs populate the Iceberg-backed transformation layer. Job status is monitored until processing succeeds.

<a id='4-3'></a>
### 4.3. Serving Zone

The serving layer uses Amazon Redshift as the analytical warehouse. Redshift Spectrum exposes the Iceberg tables through the Glue Catalog without requiring a full reload into native Redshift tables.

The serving IAM configuration defines the permissions required by the Redshift-based serving layer.

The serving module provisions the Redshift resources used by the analytical warehouse.

The root Terraform configuration connects the serving module to the complete data platform.

The serving module completes deployment of the three-layer data lake and prepares Redshift for analytical modeling.

<a id='5'></a>
## 5. Data Modeling with dbt and Redshift Spectrum

The final stage turns the transformed Iceberg datasets into a curated analytical model for reporting and business analysis.

<a id='5-1'></a>
### 5.1. Redshift Setup

Redshift Spectrum connects the warehouse to the Glue Catalog and enables direct querying of Iceberg tables stored in S3. Terraform creates the external schema and the target serving schema.

<span style="font-size:16px"></span> Make sure you're in the `terraform` directory and run the serving module with the following command:
<div style="padding: 10px 2px 0px 4px; border-radius: 4px;border: 1px solid #99999955;box-shadow: 4px 4px 6px rgba(52, 51, 51, 0.1);width: 90%;">

```bash
terraform apply -target=module.serving
```
</div>

The serving Terraform module creates the Redshift schemas required for external Iceberg access and curated models.

<a id='5-2'></a>
### 5.2. Redshift Validation

The following checks confirm that Redshift can access both the external Iceberg schema and the serving database schema.

Redshift connection settings are configured from the deployed cluster endpoint.

In [24]:
REDSHIFTDBHOST = 'de-c4w4a1-redshift-cluster.c3boili8odoz.us-east-1.redshift.amazonaws.com'
REDSHIFTDBPORT = 5439
REDSHIFTDBNAME = 'dev'
REDSHIFTDBUSER = 'defaultuser'
REDSHIFTDBPASSWORD = 'Defaultuserpwrd1234+'

redshift_connection_url = f'postgresql+psycopg2://{REDSHIFTDBUSER}:{REDSHIFTDBPASSWORD}@{REDSHIFTDBHOST}:{REDSHIFTDBPORT}/{REDSHIFTDBNAME}'
%sql {redshift_connection_url}

The schema query verifies that the expected external and serving schemas are available in the development database.

In [25]:
%sql SHOW SCHEMAS FROM DATABASE dev

 * postgresql+psycopg2://defaultuser:***@de-c4w4a1-redshift-cluster.c3boili8odoz.us-east-1.redshift.amazonaws.com:5439/dev
   postgresql+psycopg2://postgresuser:***@de-c4w4a1-rds.czg8aoiowmjf.us-east-1.rds.amazonaws.com:5432/postgres
4 rows affected.

[('dev', 'deftunes_serving', 100, 'local', None, None, None),
 ('dev', 'deftunes_transform', 100, 'external', None, 'de_c4w4a1_silver_db', '{"IAM_ROLE":"arn:aws:iam::730335556635:role/de-c4w4a1-load-role"}'),
 ('dev', 'information_schema', 1, 'local', 'rdsdb=UCDA/rdsdb~=U/rdsdb', None, None),
 ('dev', 'public', 1, 'local', 'rdsdb=UCDA/rdsdb~=UC/rdsdb', None, None)]

The external schema is inspected to confirm that the Glue Catalog’s Iceberg tables are visible to Redshift.

In [26]:
%sql SHOW TABLES FROM SCHEMA dev.deftunes_transform

 * postgresql+psycopg2://defaultuser:***@de-c4w4a1-redshift-cluster.c3boili8odoz.us-east-1.redshift.amazonaws.com:5439/dev
   postgresql+psycopg2://postgresuser:***@de-c4w4a1-rds.czg8aoiowmjf.us-east-1.rds.amazonaws.com:5432/postgres
3 rows affected.

[('dev', 'deftunes_transform', 'sessions', 'EXTERNAL TABLE', '', '', None, None, None, None, 'DATA CATALOG TABLE'),
 ('dev', 'deftunes_transform', 'songs', 'EXTERNAL TABLE', '', '', None, None, None, None, 'DATA CATALOG TABLE'),
 ('dev', 'deftunes_transform', 'users', 'EXTERNAL TABLE', '', '', None, None, None, None, 'DATA CATALOG TABLE')]

The query below validates that Redshift Spectrum can read records from the Iceberg tables.

In [27]:
%sql select * from deftunes_transform.songs limit 10

 * postgresql+psycopg2://defaultuser:***@de-c4w4a1-redshift-cluster.c3boili8odoz.us-east-1.redshift.amazonaws.com:5439/dev
   postgresql+psycopg2://postgresuser:***@de-c4w4a1-rds.czg8aoiowmjf.us-east-1.rds.amazonaws.com:5432/postgres
10 rows affected.

[('TRWPGPF12903CB1338', "Put 'Em In A Box_ Tie 'Em With A Ribbon (And Throw 'Em In The Deep Blue Sea)", 'SOYXLKL12AB018BA8E', "Here's Steve Lawrence", 'ARVY7RE1187B9909BE', '38931c3d-5e87-461b-8982-84428d8a5a5d', 'Steve Lawrence', 143.856, 0.521343, 0.376127, 0, 6408048, -1, 0, datetime.date(2026, 7, 19), 'postgres_rds'),
 ('TRTOZLA128F931A269', "I Got It Bad (And That Ain't Good)", 'SOJLZTQ12AB017EB6A', "Love Letters from Maureen O'Hara - Yvonne De Carlo Sings", 'ARXWF151187FB40C2E', '1163dff9-28ef-4657-892f-e807d398d1bf', 'Yvonne De Carlo', 167.497, 0.291912, 0.0, 0, 4550282, -1, 0, datetime.date(2026, 7, 19), 'postgres_rds'),
 ('TRBNLYJ128E0797F96', 'Blues for Los Angeles', 'SOTGQIC12A67AE225A', 'Les Incontournables du Jazz', 'AROK4SL1187FB54666', 'a21318db-f228-4a4d-8bce-6947a62985a5', 'Bill Frisell', 669.387, 0.752383, 0.449503, 1998, 192966, -1, 0, datetime.date(2026, 7, 19), 'postgres_rds'),
 ('TRYOYNM128F4275659', 'Sonata in A minor - Allegretto ben Moderato', 'SOEOZIX12A8C13748E', 'La Flute Francaise', 'ARNNHKF1187B9B4484', 'e9b169f4-13c8-45aa-8b27-6ff023d1d309', 'Paul Fried  - Mark Kroll', 345.182, 0.20073, 0.0, 0, 994987, -1, 0, datetime.date(2026, 7, 19), 'postgres_rds'),
 ('TRSGHLA128F42281CD', 'Conmigo', 'SOWKXIF12A6D4FCEF4', 'Grande', 'AREH95O1187B9B9EB0', 'faabf02e-8247-4b6f-bfc3-d3b3a1bb2969', 'Los Galvan', 179.853, 0.473155, 0.197821, 0, 1282979, -1, 0, datetime.date(2026, 7, 19), 'postgres_rds'),
 ('TRFPMYT128F428531A', 'The End Of Words (Remastered)', 'SOLEKMF12A8C13E9E2', 'Aion (Remastered)', 'ARF8ZJW1187B98C949', 'ccda046a-2674-4f7d-97e6-f23d6c156432', 'Dead Can Dance', 126.406, 0.745119, 0.502886, 0, 2385919, -1, 0, datetime.date(2026, 7, 19), 'postgres_rds'),
 ('TRMOAZN128F42AC8D9', 'Wenn die Börsianer tanzen', 'SOBYJKA12A8C140496', 'Am Flussufer - Live', 'ARQ24CC1187B9969F9', '4e1d5be7-6736-4af3-8ac8-619fabc57818', 'Konstantin Wecker', 192.914, 0.550279, 0.428905, 2001, 3465286, -1, 0, datetime.date(2026, 7, 19), 'postgres_rds'),
 ('TRLBXMB128F92E0933', 'Yellow Zone', 'SODOHGH12AAF3B2840', 'Kings of Psychobilly ~ a 5 Disc Career', 'ARTS88P1187B9A7E6C', '8df95482-901f-469f-a268-73b34e05dad9', 'Meteors', 142.21, 0.620078, 0.412488, 1988, 4256591, -1, 0, datetime.date(2026, 7, 19), 'postgres_rds'),
 ('TRDQOAF128F92E37A8', 'Sometimes', 'SOMEDPV12AB017BFC0', 'The Definitive Collection', 'ARX1CYE1187FB3A97B', '189ede50-9c85-48b8-bae2-cb44ccd5b5c9', 'Bill Anderson / Mary Lou Turner', 172.564, 0.464699, 0.354208, 0, 4270811, -1, 0, datetime.date(2026, 7, 19), 'postgres_rds'),
 ('TROXYMO128F427E974', 'English Suite No. 3 in G minor_  BWV 808/Allemande', 'SOFZQGL12A8C13626D', 'Bach: English Suites Nos. 1_ 3 & 6 [Expanded Edition]', 'AR0IHC91187B9B1347', '71131221-cda2-4d28-8348-4574412d9c9f', 'Murray Perahia', 200.28, 0.552172, 0.450356, 0, 3274278, -1, 0, datetime.date(2026, 7, 19), 'postgres_rds')]

In [28]:
%sql select * from deftunes_transform.sessions limit 10

 * postgresql+psycopg2://defaultuser:***@de-c4w4a1-redshift-cluster.c3boili8odoz.us-east-1.redshift.amazonaws.com:5439/dev
   postgresql+psycopg2://postgresuser:***@de-c4w4a1-rds.czg8aoiowmjf.us-east-1.rds.amazonaws.com:5432/postgres
5 rows affected.

[('7118b8ac-75fe-426a-bf6c-09044ed64011', '579ef099-ffed-410c-916a-05c222d7a734', 'TRRKCXY128F42B08EC', 'Majestic', 'ARPNILO1187B9B59BB', 'Journey', 0.89, 'USD', True, '2021-04-18T22:54:45.137434', 'Opera/8.77.(X11; Linux x86_64; lb-LU) Presto/2.9.170 Version/11.00', '2020-01-28T20:10:19.161986', datetime.date(2026, 7, 19)),
 ('7118b8ac-75fe-426a-bf6c-09044ed64011', '579ef099-ffed-410c-916a-05c222d7a734', 'TRACVFS128F424CF67', 'We Cry As One', 'ARIGHFP1187B9A4467', 'The Old Dead Tree', 1.85, 'USD', False, None, 'Opera/8.77.(X11; Linux x86_64; lb-LU) Presto/2.9.170 Version/11.00', '2020-01-28T20:10:19.161986', datetime.date(2026, 7, 19)),
 ('7118b8ac-75fe-426a-bf6c-09044ed64011', '579ef099-ffed-410c-916a-05c222d7a734', 'TRWWMUJ128F932FAFF', 'Thugz Of War', 'ARJNOOU11F4C845A6A', 'Riviera Regime', 1.44, 'USD', False, None, 'Opera/8.77.(X11; Linux x86_64; lb-LU) Presto/2.9.170 Version/11.00', '2020-01-28T20:10:19.161986', datetime.date(2026, 7, 19)),
 ('7118b8ac-75fe-426a-bf6c-09044ed64011', '579ef099-ffed-410c-916a-05c222d7a734', 'TRYQJNT128F429B976', 'Last Train', 'AREJC2N1187FB555F9', 'Dare', 1.85, 'USD', True, '2023-06-10T11:22:42.309662', 'Opera/8.77.(X11; Linux x86_64; lb-LU) Presto/2.9.170 Version/11.00', '2020-01-28T20:10:19.161986', datetime.date(2026, 7, 19)),
 ('7118b8ac-75fe-426a-bf6c-09044ed64011', '579ef099-ffed-410c-916a-05c222d7a734', 'TRXWVQV12903CE7B2E', 'Self Doubt Gun', 'ARN4IYF1187FB49D76', 'Pagan Wanderer Lu', 0.33, 'USD', False, None, 'Opera/8.77.(X11; Linux x86_64; lb-LU) Presto/2.9.170 Version/11.00', '2020-01-28T20:10:19.161986', datetime.date(2026, 7, 19))]

In [29]:
%sql select * from deftunes_transform.users limit 10

 * postgresql+psycopg2://defaultuser:***@de-c4w4a1-redshift-cluster.c3boili8odoz.us-east-1.redshift.amazonaws.com:5439/dev
   postgresql+psycopg2://postgresuser:***@de-c4w4a1-rds.czg8aoiowmjf.us-east-1.rds.amazonaws.com:5432/postgres
10 rows affected.

[('90b33325-f5bd-4c43-a90b-168836b16d49', 'Ferguson', 'Katherine', '2020-01-29T17:55:57.719494', datetime.date(2026, 7, 19), '50.598427', '13.610242', 'Litvínov', 'CZ', 'Europe/Prague', '2026-07-19 14:07:25'),
 ('9d458d10-0b5d-4426-9d01-993e9597226b', 'Gardner', 'Christopher', '2020-01-09T17:29:36.635959', datetime.date(2026, 7, 19), '13.51825', '99.95469', 'Damnoen Saduak', 'TH', 'Asia/Bangkok', '2026-07-19 14:07:25'),
 ('43eafcf6-620a-4eea-b8c5-0cb5cef29e34', 'Chavez', 'James', '2020-01-28T19:44:57.976367', datetime.date(2026, 7, 19), '45.47885', '133.42825', 'Lesozavodsk', 'RU', 'Asia/Vladivostok', '2026-07-19 14:07:25'),
 ('7246fbc0-d1fd-4de3-b4d3-fbd7a884b8e9', 'Mejia', 'Kelly', '2020-01-21T21:32:55.223506', datetime.date(2026, 7, 19), '48.98693', '2.44892', 'Gonesse', 'FR', 'Europe/Paris', '2026-07-19 14:07:25'),
 ('80aab7ab-48a2-4476-ae87-41ce40f71c25', 'Lewis', 'Barry', '2020-01-26T19:00:15.272554', datetime.date(2026, 7, 19), '53.16167', '6.76111', 'Hoogezand', 'NL', 'Europe/Amsterdam', '2026-07-19 14:07:25'),
 ('f1fcedc0-0b78-45e1-a4c4-06cb5fac3370', 'Peck', 'Kenneth', '2020-01-30T21:33:08.448189', datetime.date(2026, 7, 19), '43.31667', '-2.68333', 'Gernika-Lumo', 'ES', 'Europe/Madrid', '2026-07-19 14:07:25'),
 ('2072178f-5ff1-46be-b3ad-0288fe705da3', 'Warren', 'Jo', '2020-01-30T03:45:56.479523', datetime.date(2026, 7, 19), '-19.32556', '-41.25528', 'Resplendor', 'BR', 'America/Sao_Paulo', '2026-07-19 14:07:25'),
 ('221ec393-6d1b-4047-9b5d-647b6ecaca3d', 'Callahan', 'Kathryn', '2020-01-24T07:04:50.825472', datetime.date(2026, 7, 19), '39.09112', '-94.41551', 'Independence', 'US', 'America/Chicago', '2026-07-19 14:07:25'),
 ('e55206f6-47b7-4d32-8b03-253089853de2', 'Harris', 'Brendan', '2020-01-26T13:51:00.911375', datetime.date(2026, 7, 19), '35.50056', '117.63083', 'Pingyi', 'CN', 'Asia/Shanghai', '2026-07-19 14:07:25'),
 ('4372a6a9-8336-4f80-8252-f43643881161', 'Howell', 'Emily', '2020-01-28T07:40:50.915585', datetime.date(2026, 7, 19), '9.91861', '-68.30472', 'Tinaquillo', 'VE', 'America/Caracas', '2026-07-19 14:07:25')]

<a id='5-3'></a>
### 5.3. dbt Setup

A dbt project provides version-controlled SQL transformations, documentation, testing, and materialization of the serving-layer model in Redshift.

The dbt project is initialized with Redshift as its target warehouse.

The dbt profile defines the Redshift connection and the target `deftunes_serving` schema.

<span style="font-size:16px"><b>5.3.2.</b></span> To test the connection, run the following commands:
<div style="padding: 10px 2px 0px 4px; border-radius: 4px;border: 1px solid #99999955;box-shadow: 4px 4px 6px rgba(52, 51, 51, 0.1);width: 50%;">

```bash
cd dbt_modeling
dbt debug
```
</div>

`dbt debug` validates the project configuration and warehouse connection.

If everything was correctly configured, you should see the following text at the end of the output:

```bash
Connection test: [OK connection ok]
```

A successful connection test confirms that dbt can communicate with Redshift.

<a id='5-4'></a>
### 5.4. Data Modeling

The serving layer is organized as a star schema with fact and dimension models materialized as tables.

The dbt models define the fact and dimension tables, while `schema.yml` documents and tests the model. The serving-layer models are built with `dbt run`.

Sample queries can be used to validate the resulting serving tables and confirm that the modeled relationships produce usable analytical data.
E.g.,  
%sql SHOW TABLES FROM SCHEMA dev.deftunes_serving  
%sql SELECT * FROM deftunes_serving.<TABLE_NAME> limit 10

## Conclusion

This project demonstrates an end-to-end cloud data engineering workflow: multi-source ingestion, medallion data lake design, Iceberg-based transformation, infrastructure as code, Redshift Spectrum integration, and dbt star-schema modeling. The architecture provides a foundation for future orchestration, data-quality checks, and visualization.